---
groups:
- name: images
  jobs: [build-task-image, build-docker-machine-setup]
- name: docker-machine
  jobs: [provision-docker-host]

jobs:
- name: build-hab-ci
  serial: true
  plan:
    - {get: pipeline-ci-image, trigger: true}
    - put: docker-image-ci
      params:
        build: pipeline-ci-image/ci/ci_image

- name: build-hab-delmo
  serial: true
  plan:
    - {get: pipeline-ci-image, trigger: true}
    - put: docker-image-ci
      params:
        build: images/docker

- name: build-docker-machine-setup
  serial: true
  plan:
    - {get: docker-machine-setup, trigger: true}
    - put: docker-machine-setup-image
      params:
        build: docker-machine-setup/images/docker-machine-setup

resources:

- name: delmo-ci
  type: git
  source:
    uri: https://github.com/bodymindarts/delmo
    branch: {{pipeline-branch}}

- name: delmo
  type: git
  source:
    uri: git@github.com:bodymindarts/delmo.git
    branch: {{pipeline-branch}}
    private_key: {{github-key}}

- name: delmo-all
  type: git-multibranch
  source:
    uri: https://github.com/bodymindarts/delmo
    branches: '.*'
    ignore_branches: 'master'

- name: pipeline-ci-image
  type: git
  source:
    uri: https://github.com/bodymindarts/delmo
    branch: {{pipeline-branch}}
    paths: [ci/ci_image/*]

- name: docker-image-ci
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: bodymindarts/delmo-pipeline

- name: docker-machine-setup
  type: git
  source:
    uri: https://github.com/eeyun/hab-ci
    branch: {{pipeline-branch}}
    private_key: {{github-key}}
    paths: [images/docker-machine-setup/*]

- name: delmo-release
  type: github-release
  source:
    user:         {{github-user}}
    repository:   delmo
    access_token: {{github-token}}

- name: docker-machine-setup-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: eeyun/docker-machine-setup

- name: hab-delmo-image
  type: docker-image
  source:
      email: {{docker-hub-email}}
      username: {{docker-hub-username}}
      password: {{docker-hub-password}}
      repository: eeyun/hab-delmo

